<?php
    /**
     * @var $this CI_Loader|App
     */
    echo Component::Sidebar([
        'options' => ['header' => 'MENU PRINCIPAL'],
        /**
         * This menu was generated by the system, please do not touch this file manually.
         */
        'nodes' =>
            [
                    ['label' => 'Managers', 'url' => '', 'options' => ['icon' => 'fa fa-bookmark'],
                     'nodes' =>
                        [
						['label' => 'Crear manager', 'url' => 'managers/crearmanager', 'options' => ['icon' => 'fa fa-user-plus']],
						['label' => 'Managers', 'url' => 'managers', 'options' => ['icon' => 'fa fa-list']],

						],],['label' => 'Courses', 'url' => '', 'options' => ['icon' => 'fa fa-bookmark'],
                     'nodes' =>
                        [
						['label' => 'Crear curso', 'url' => 'courses/crearcourse', 'options' => ['icon' => 'fa fa-user-plus']],
						['label' => 'Listado cursos', 'url' => 'courses', 'options' => ['icon' => 'fa fa-list']],

						],],['label' => 'Tests', 'url' => '', 'options' => ['icon' => 'fa fa-bookmark'],
                     'nodes' =>
                        [
						['label' => 'Crear test', 'url' => 'tests/creartest', 'options' => ['icon' => 'fa fa-user-plus']],
						['label' => 'Listado tests', 'url' => 'tests', 'options' => ['icon' => 'fa fa-list']],

						],],            ]
    ]);
?>

<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">