<?php
    $nav = new NavLib;
    $nodes = $_POST['NODES'];
    $na
?>
<?= "<?php\n" ?>
    /**
     * @var $this CI_Loader|App
     */
    echo Component::Sidebar([
        'options' => ['header' => 'MENU PRINCIPAL'],
        /**
         * This menu was generated by the system, please do not touch this file manually.
         */
        'nodes' =>
            [
                    <?= $nav->AssemblyNodes($nodes) ?>
            ]
    ]);
?>

<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">